//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcStokEntities : DbContext
    {
        public DbMvcStokEntities()
            : base("name=DbMvcStokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_kategori> Tbl_kategori { get; set; }
        public virtual DbSet<Tbl_musteri> Tbl_musteri { get; set; }
        public virtual DbSet<Tbl_personel> Tbl_personel { get; set; }
        public virtual DbSet<Tbl_satislar> Tbl_satislar { get; set; }
        public virtual DbSet<Tbl_urunler> Tbl_urunler { get; set; }
        public virtual DbSet<Tbl_admin> Tbl_admin { get; set; }
    }
}
